name: Pig Chat
version: '${project.version}'
main: ru.pigtu.pigchat.PigChat
api-version: '1.20'
description: Design your own server chat with placeholders from PlaceholdersAPI
website: https://impigtu.github.io/pig
authors: [ PigTu ]
commands:
  pigchat:
    aliases: pig
    permission: pig.reload
